### PR TITLE
Add GitLab Web IDE

### PR DESCRIPTION
**Pull request by dosire**
https://news.ycombinator.com/item?id=17323020

### CODE REVIEW

**Comment by styfle** [comment]
Hi Sytse, thanks for the PR!

Can you execute code with the GitLab IDE?

**Comment by greenled** [comment]
@styfle well...not yet. but there is a prototype! Check http://disq.us/p/1t9omq8

**Comment by jayvdb** [comment]
Is it still based on Koding?
https://venturebeat.com/2016/07/26/koding-gitlab/

**Comment by benatkin** [comment]
This feature should cover that requirement: Interactive Web Terminals for the Web IDE https://docs.gitlab.com/ee/user/project/web_ide/#interactive-web-terminals-for-the-web-ide-ultimate-only

**Pull request closed without merging**
