### PR TITLE
Replace codenvy line by Eclipse Che

### PR DESCRIPTION
**Pull request by benoitf**
Codenvy has been acquired by Red Hat
Eclipse Che has now almost all features of codenvy that have been open sourced.

### CODE REVIEW

**Comment by styfle** [comment]
Hi Florent, it looks like the Eclipse Che website just links back to CodeEnvy.



Also, the GitHub repos seems to be run independently with new commits to CodeEnvy in 2018.




What is the purpose of removing the CodeEnvy links?

**Comment by benoitf** [comment]
codenvy only provides old che 5.x versions. Now codenvy.io is no longer developed. ( note that I'm committer on both che and codenvy)
Links on che website will soon be replaced

**Comment by benoitf** [comment]
A new online version of che is provided but it is no longer at codenvy.io

**Comment by styfle** [comment]
Ok thanks for clearing that up.

However, the description does not match the [contributing.md](https://github.com/styfle/awesome-online-ide/blob/master/contributing.md) guidelines.

Please revise, thanks 👍

**Comment by benoitf** [comment]
OK thx will do

**Pull request closed without merging**
