### PR TITLE
Add new snippets

### PR DESCRIPTION
**Pull request by petermbenjamin**
* Add Go Playground
* Add SQLFiddle

### CODE REVIEW

**Comment by styfle** [comment]
Thanks for the PR! 👍 

It looks like you added Go Playground at the top of the list. Can you move it to the bottom of the list?

**Comment by petermbenjamin** [comment]
Moved to bottom of the list.

Would it make sense to organize the resources alphabetically?

**Comment by styfle** [comment]
Thanks!

**Comment by styfle** [comment]
I need to think through order a little bit more but I want higher quality results first so that's why Full IDEs are at the top.

**Pull request merged**
