### PR TITLE
Add Devello Studio

### PR DESCRIPTION
**Pull request by DevelloStudio**
Devello Studio is first and foremost an IDE specifically designed for web development, supporting you in almost all aspects of the process, from coding to release. There are several methods available for creating a project. You can either start something from scratch and then create your own structure or import a project from anywhere on your local system (as a ZIP file) or even over the web. For the time being, you can import projects from FTP servers or GitHub repositories. Currently two modes are supported for releasing your product, either via Github or FTP. You can create both public and private projects, and each project can contain unlimited number of files and folders according to your needs.
You can immediately start using this online development environment either by creating a project, opening a public project and extending it or forking it to keep the main version intact and having your own project. Although registering is not mandatory but you may take advantage of many extra features available for registered users such as being able to create private projects or the option to making your public projects read-only.
You can make your own Devello Studio account or use your GitHub or Google accounts to login. Logging using GitHub account enables you to commit your projects to GitHub repositories or even sync your project with a repo, so you never miss anything.
Public projects can be explored and viewed by all users via explore menu in the landing page.
An interesting feature of Devello Studio is that you can practically keep on working exactly where you had left off your project last time, open files will be loaded as before and last file you were previously working on will be active again, and not only that, but also cursor position will be restored.
Adding content to projects can be a real headache particularly when you have to deal with several items, but we allow you to add folder trees (folders containing files and other folders) using drag and drop, also you are able to compress your contents in a ZIP file and let it be uploaded and automatically extracted into your project.

Thanks in advance 👍

### CODE REVIEW

**Comment by styfle** [comment]
I visited the website and clicked new project, gave it a name, and then nothing happened.

Then I tried opening an existing project and modifying the code but it doesn't show intellisense errors like the description implies.

**Comment by DevelloStudio** [comment]
Hi,

This IDE is inspired by Visual Studio, so everything starts from the treeview (accessible from Project Explorer). If you have made an empty project, then you should add files or files (either manually by right clicking on the project node or dragging and dropping files from your local system). And if you have created an standard template, your project will contain a minimum set of files (I think it's what you've done). You just have to write your code in the respective files, is there anything special that I've missed? The whole process is explained with further details in tutorial videos as well.

In order to view the possible errors/warning, you should first switch to a preview mode, then from the pane located at the bottom of the preview, click on the button at the right of the screen. This button will be red if code contains any errors/warnings. Currently JSHint is used for verifying code integrity. Once you click on the right part of the error message (containing filename and line number), you'll be forwarded to the line raising the error. All details are demonstrated in docs and also tutorial videos.

**Comment by styfle** [comment]
The design is very confusing. Here's what I tried:

1. File > New Project. Then I see a modal popup.
2. Input both "name" and "project name" in the modal
3. Selected "Standard Web Project" radio button in the modal
4. Clicked "Create Project" button at the bottom of the modal

Then the modal disappeared and nothing else happened.

Then I tried "File > New File" but it is disabled ([see screenshot](https://user-images.githubusercontent.com/229881/89134878-b14edb80-d4f6-11ea-93ea-f7fa2d2eb6d1.png))

Then I gave up 🤷‍♂️

**Comment by styfle** [comment]
> then you should add files or files (either manually by right clicking on the project node

I don't see a project node?

[See complete screenshot](https://user-images.githubusercontent.com/229881/89134915-0a1e7400-d4f7-11ea-90e3-1088c14b2451.png)

**Comment by DevelloStudio** [comment]
Hi,

hmm, sorry for the inconvenience, I think you have right. First of all the item "New File" should be removed from File menu, as it does nothing at the moment, and everything happens in treeview located in project explorer (in the 2nd screenshot sent by you, it's located in the right-most side of the screen, just click on the "Project Explorer" tab and the slider will open up. I think this tab needs to open (visible) by default, so users can view it right away, without having to do any extra click. Your project already has a minimum set of files.
The "name" textbox in project creation wizard is optional, you can leave it empty as well.
Thanks for your attention.

**Comment by styfle** [comment]
I'm going to close this since it sounds like Devello Studio is not ready for general usage.

This is a curated list and I don't think it makes the cut its current state.

**Pull request closed without merging**
